### ISSUE TITLE
Readme should not specify IP address

### ISSUE THREAD

**Issue by shapeshed** [clearmatics/validator-dapp#6]
The README specifies an IP Address but given the DApp can be deployed against any network this should be abstracted from the README.

**Comment by eastata** [comment]
increase requirements:
- rpc entrypoint should be defined as env vars
- rpc entrypoint should be defined as env vars or option for docker container 
- rpc entrypoint should support dns resolution

**Comment by shapeshed** [comment]
Isn't this defined the custom RPC endpoint in MetaMask?

**Comment by eastata** [comment]
> Isn't this defined the custom RPC endpoint in MetaMask?

at the several places
https://github.com/clearmatics/validator-dapp/blob/cc4bfed504af99a02855717331e024b18ccac911/truffle.js#L8

**Comment by shapeshed** [comment]
I see - I think this is for development purposes and that when the DApp is built for production it is agnostic to the RPC endpoint. @therealdannzor could you confirm this?

**Comment by therealdannzor** [comment]
It is possible to switch between RPC endpoints in real time by using Metamask (i.e. switching between prod and dev network). If I understand the current implementation correctly, it should be the case @shapeshed.

**Comment by shapeshed** [comment]
OK so in terms of DevOps deployment I don't think there needs to be any configuration.

**Comment by eastata** [comment]
We already have configured prod env and validator dapp at https://validator-dapp.autonity.io/validators
Also I have configured metamask and can successfully connect to prod

I have deployed new network to new enviromet: (name autonity2)
- build new cluster
- generate validators keys
- generate genesis.json
- run autonity init for each validator
- network start to mine new blocks

I forward RPC port from autonity2 to local
Configure metamask to http://127.0.0.1:8545
Import to account key of validator-0 
I can:
- see the balance of validator-0
- sent money from validator-0 and transaction confirmed

Open https://validator-dapp.autonity.io/validators (metamask setted to prod network) - can see validator list
Switch metamask to autonity2 - can see only blue screen

Is it kind of strange metamask behavior?
Is it wrong config of new autonity2 network?
